### PR TITLE
Tempus 27 application computation linking

### PR DESCRIPTION
**Pull request by jetinder20**

### CODE REVIEW

**Comment by cherrera2001** [comment]
what happens if there are no computations, will the application be flagged as invalid?

**Comment by jetinder20** [comment]
Yes. The application is flagged invalid if there are no rules or mini dashboard or a computation job is assigned to it. However it is still valid if a dashboard is unassigned.

**Comment by jetinder20** [comment]
I have pushed code for few more cards to the same branch only as its not merged with dev yet and these cards have dependency on the code which is not merged yet.

**Comment by cherrera2001** [comment]
api checks out, code is clean. merged

**Pull request merged**
