### PR TITLE
Tempus 186

### PR DESCRIPTION
**Pull request by Himanshu-it**
This PR contains:

1. Ingesting unit comming with telemetry timeseries and depthseries data to tag_metadata table.
2. The json format is : {"values":{"humidity":{"unit":"%","value":15.616},"viscosity":{"unit":"cgs","value":0.158}, "ts":1526804557313}}
3. For sparkplug add unit as a json to metric.metadata e.g {"unit":"unit"}, refer AbstractMqttTelemetryIntegrationTest.java

4. Fix for application test case failing because of conflicting dependencies with sparkplug-java jar.

5. Fix for issue 372. Moving schema changes of adding ts_diff, ds_diff for ts_kv, ds_kv and creation of tag_metadata table to an upgrade script.

### CODE REVIEW

**Comment by jayeshkapadnis** [comment]
Please Rebase your branch with Dev and check why Travis CI build is failing

**Comment by cherrera2001** [comment]
@jayeshkapadnis yes the object is no longer KV, but unit is optional to ensure backwards compatibility. Is your concern around the object, or the data model in cql/sql?

**Comment by cherrera2001** [comment]
@Himanshu-it can you please merge from dev and fix the conflicts...I completed the review and it seems like it will be ok.

**Comment by Himanshu-it** [comment]
Rebased with latest dev.

**Pull request merged**
